name: focusnflow
description: A Flutter project.

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3

  intl: ^0.20.2